let themes = @[
  Theme(
    rowNum:     TextColor(fg: fgWhite,   hi: false),
    rowNumHi:   TextColor(fg: fgWhite,   hi: true),
    note:       TextColor(fg: fgCyan,    hi: true),
    noteNone:   TextColor(fg: fgCyan,    hi: false),
    sample:     TextColor(fg: fgWhite,   hi: true),
    sampleNone: TextColor(fg: fgWhite,   hi: false),
    effect:     TextColor(fg: fgMagenta, hi: true),
    effectNone: TextColor(fg: fgMagenta, hi: false),
    border:     TextColor(fg: fgBlack,   hi: true),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgWhite,   hi: true),
    textHi:     TextColor(fg: fgCyan,    hi: true),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgMagenta
  ),
  Theme(
    rowNum:     TextColor(fg: fgWhite,   hi: false),
    rowNumHi:   TextColor(fg: fgWhite,   hi: true),
    note:       TextColor(fg: fgGreen,   hi: true),
    noteNone:   TextColor(fg: fgGreen,   hi: false),
    sample:     TextColor(fg: fgCyan,    hi: true),
    sampleNone: TextColor(fg: fgCyan,    hi: false),
    effect:     TextColor(fg: fgBlue,    hi: true),
    effectNone: TextColor(fg: fgBlue,    hi: false),
    border:     TextColor(fg: fgWhite,   hi: false),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgGreen,   hi: true),
    textHi:     TextColor(fg: fgYellow,  hi: true),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgCyan
  ),
  Theme(
    rowNum:     TextColor(fg: fgWhite,   hi: false),
    rowNumHi:   TextColor(fg: fgWhite,   hi: true),
    note:       TextColor(fg: fgCyan,    hi: true),
    noteNone:   TextColor(fg: fgCyan,    hi: false),
    sample:     TextColor(fg: fgYellow,  hi: true),
    sampleNone: TextColor(fg: fgYellow,  hi: false),
    effect:     TextColor(fg: fgGreen,   hi: true),
    effectNone: TextColor(fg: fgGreen,   hi: false),
    border:     TextColor(fg: fgBlack,   hi: true),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgWhite,   hi: false),
    textHi:     TextColor(fg: fgGreen,   hi: true),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgYellow
  ),
  Theme(
    rowNum:     TextColor(fg: fgMagenta, hi: false),
    rowNumHi:   TextColor(fg: fgMagenta, hi: true),
    note:       TextColor(fg: fgCyan,    hi: true),
    noteNone:   TextColor(fg: fgCyan,    hi: false),
    sample:     TextColor(fg: fgBlue,    hi: true),
    sampleNone: TextColor(fg: fgBlue,    hi: false),
    effect:     TextColor(fg: fgMagenta, hi: true),
    effectNone: TextColor(fg: fgMagenta, hi: false),
    border:     TextColor(fg: fgBlack,   hi: true),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgWhite,   hi: true),
    textHi:     TextColor(fg: fgMagenta, hi: true),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgBlue
  ),
  Theme(
    rowNum:     TextColor(fg: fgWhite,   hi: false),
    rowNumHi:   TextColor(fg: fgWhite,   hi: true),
    note:       TextColor(fg: fgWhite,   hi: true),
    noteNone:   TextColor(fg: fgBlack,   hi: true),
    sample:     TextColor(fg: fgWhite,   hi: false),
    sampleNone: TextColor(fg: fgBlack,   hi: true),
    effect:     TextColor(fg: fgWhite,   hi: true),
    effectNone: TextColor(fg: fgBlack,   hi: true),
    border:     TextColor(fg: fgBlack,   hi: true),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgWhite,   hi: false),
    textHi:     TextColor(fg: fgYellow,  hi: false),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgYellow
  ),
  Theme(
    rowNum:     TextColor(fg: fgWhite,   hi: false),
    rowNumHi:   TextColor(fg: fgWhite,   hi: true),
    note:       TextColor(fg: fgCyan,    hi: true),
    noteNone:   TextColor(fg: fgBlack,   hi: true),
    sample:     TextColor(fg: fgCyan,    hi: false),
    sampleNone: TextColor(fg: fgBlack,   hi: true),
    effect:     TextColor(fg: fgWhite,   hi: true),
    effectNone: TextColor(fg: fgBlack,   hi: true),
    border:     TextColor(fg: fgBlack,   hi: true),
    muted:      TextColor(fg: fgBlack,   hi: true),
    text:       TextColor(fg: fgWhite,   hi: false),
    textHi:     TextColor(fg: fgCyan,    hi: true),
    cursor:     TextColor(fg: fgBlack,   hi: false),
    cursorBg:   bgCyan
  )
]

